### ISSUE TITLE
вывод результата для пакетного запроса

### ISSUE THREAD

**Issue by extreme-sav** [lavelinevgeny/consquery#13]
результат запроса содержит пакеты, выводиться в таблицу только один пакет

**Comment by lavelinevgeny** [comment]
Реализовано в релизе 3.1.417.

![image](https://user-images.githubusercontent.com/47559264/135748296-11ea0a2b-5391-4f53-b4ee-aa341021e3e5.png)
![image](https://user-images.githubusercontent.com/47559264/135748307-1f7c57cb-4e5a-43bd-b2c7-c2a5322ca0fe.png)
![image](https://user-images.githubusercontent.com/47559264/135748315-99778ec1-77e5-49e1-8c98-649723195f0a.png)

Видео с демонстрацией похожего функционала, но для вывода временных таблиц: https://youtu.be/UNZUBW8wZHI
